<?php

/**
 * @file
 * Contains islandora_lite_collections.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function islandora_lite_collections_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the islandora_lite_collections module.
    case 'help.page.islandora_lite_collections':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function islandora_lite_collections_theme() {
  return [
    'islandora_lite_collections' => [
      'render element' => 'children',
    ],
  ];
}
